DROP DATABASE IF EXISTS TESTFRAMEWORK;

CREATE DATABASE TESTFRAMEWORK;
USE TESTFRAMEWORK;

DROP TABLE IF EXISTS T_USER_INFO;
CREATE TABLE T_USER_INFO(
  ID INT NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(50) NOT NULL,
  LOGIN_PASSWORD VARCHAR(50),
  PRIMARY KEY (ID)
)ENGINE = innoDB DEFAULT CHARSET UTF8;